#Spawn 1:
#    World: spawn
#    X: 0
#    Y: 100
#    Z: 0

Spawn: spawn

Worlds:
    THE_END:
        - end_server_1
        - end_server_2
    NETHER:
        - nether_server_1
        - nether_server_2
    NORMAL:
        - normal_server_1
        - normal_server 2